liquibase:
  container:
    image: dawnbreather/tmp:liquibase-location
  config:
    env:
      host: postgres
      database: location
      username: postgres
      password: postgres
      changelog: changelog.yaml

postgres:
  container:
    image: postgres:12-alpine
  init:
    database: location
    password: postgres